#!/bin/bash
set -e
NTHREAD=4
# PATH=/home/enrico/bio-bin/sratoolkit.3.0.0-ubuntu64/bin:$PATH
PATH="/nfsd/bcb/bcbg/prog_9/sratoolkit.3.0.1-ubuntu64/bin":$PATH

sequences=$(awk -F '-' '{print $1}' sequences.txt| grep -vE "#" sequences.txt)

mkdir -p SRR && cd SRR

for s in $sequences; do
  echo
  echo "*** Converting $s..."
  [[ -f "${s}.fasta" || -f "${s}_1.fasta" || -f "${s}_2.fasta" ]] \
  || fasterq-dump --threads $NTHREAD --progress --fasta --split-files "$s" --outdir "$s"
  echo "*** $s converted!"
done